# This file was generated by GoReleaser. DO NOT EDIT.
class Kubetap < Formula
  desc "Kubetap is a kubectl plugin to interactively proxy Kubernetes Services with ease"
  homepage "https://github.com/soluble-ai/kubetap"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/soluble-ai/kubetap/releases/download/v0.1.3/kubetap_v0.1.3_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
    sha256 "48e803ef059af673bd94e9cf0f13b7d47b64e639851d1451113f699ced3465a2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/soluble-ai/kubetap/releases/download/v0.1.3/kubetap_v0.1.3_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e95335aebce88c8bf453cbccb7136da009ae0c787cd1bb81bbb1158decd48aad"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/soluble-ai/kubetap/releases/download/v0.1.3/kubetap_v0.1.3_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
        sha256 "1b6d6a4bb900c594c0abc0af4deb45f3a88f4f7fd454021276d1e4a70b155d62"
      else
        url "https://github.com/soluble-ai/kubetap/releases/download/v0.1.3/kubetap_v0.1.3_Linux_armv6.tar.gz", :using => CurlDownloadStrategy
        sha256 "2fc48c8113bfc2b128ef688dd33c6f75dd50a87c4ce25b79de73de374b33e5e4"
      end
    end
  end
  
  head "https://github.com/soluble-ai/kubetap.git"

  def install
    bin.install "./kubectl-tap"
  end

  def caveats; <<~EOS
    kubetap is best invoked as: $ kubectl tap
  EOS
  end

  test do
    system "#{bin}/kubectl-tap version"
  end
end
